### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.async_scanner'

### ISSUE THREAD

**Issue by ProtDos** [ef1500/Elastichunt#2]
I get this error when running: `py elastichunt.py 123.60.0.0/16 9200 -eT 16 -sT 16`. Looks like the file doesn't even exist in the utils folder. Could you fix it?

**Comment by ProtDos** [comment]
Neveremind. I messed up. Sorry.

**Comment by ProtDos** [comment]
Nevermind. Still this error.

**Comment by ef1500** [comment]
I just cloned the repository and ran the exact command you mentioned, and it ran without any issues. You might have accidentally deleted a file from your local directory, and that's why it's missing.

![image](https://user-images.githubusercontent.com/45581646/230742229-2209b7d9-cd3d-4e86-8fed-1bfacd5ae235.png)

Try running `git pull` or just reclone the repository to make sure that you've got all of the files in your directory.
